import { colorMode, css, delayHydration, directus, fonts, i18n, lodash, pinia, primevue, pwa, runtimeConfig, tailwindcss, vite } from './configs'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  // alias,
  // analyzeDir,
  // app,
  // appConfig,
  // build,
  // buildDir,
  // builder,
  // components,
  css,
  // debug,
  // dev,
  // devServer,
  // devServerHandlers,
  devtools: { enabled: true },
  // dir,
  // experimental,
  // extends,
  // extensions,
  // features,
  // feture,
  // generate,
  // hooks,
  // ignore,
  // ignoreOptions,
  // ignorePrefix,
  // imports,
  // logLevel,
  modules: [// "@nuxt/scripts",
    ['nuxt-delay-hydration', delayHydration],
    // '@vueuse/nuxt',
    ['@nuxtjs/i18n', i18n], // "@nuxt/image",
    // ['@nuxtjs/seo', seo],
    // '@nuxt/test-utils/module',
    // ['@nuxt/content', content],
    // ['@nuxthq/studio', studio],
    // '@unlighthouse/nuxt',
    ['@nuxt/fonts', fonts],
    ['@vite-pwa/nuxt', pwa], // ['@unlighthouse/nuxt', unlighthouse],
    ['@pinia/nuxt', pinia],
    '@pinia-plugin-persistedstate/nuxt',
    ['nuxt-primevue', primevue],
    ['@nuxtjs/tailwindcss', tailwindcss],
    ['@nuxtjs/color-mode', colorMode], // ['@nuxtjs/strapi', strapi],
    ['nuxt-lodash', lodash],
    ['nuxt-directus', directus],
  ],
  // modulesDir,
  // nitro,
  // optimization,
  // pages,
  // plugins,
  // rootDir,
  // routeRules,
  // router,
  runtimeConfig,
  // serverDir,
  // serverHandlers,
  // sourcemap,
  // spaLoadingTemplate,
  // srcDir,
  // ssr,
  // telemetry,
  // test,
  // theme,
  // typescript,
  vite,
  // vue,
  // watch,
  // watchers,
  // workspaceDir,
})
